name: sdx
channels:
  - conda-forge
  - defaults

dependencies:
  - python >=3.10,<=3.13
  - pip
  - poetry
  - nodejs  # used by semantic-release
  - tesseract
  # - libmagic  <-- removed, not supported on Windows
  - pip:
      - paginate==0.5.6  # distlib issue
