"""Add normalized tables for research app.

Revision ID: 2cbf5c81b941
Revises:
Create Date: 2025-09-16 23:29:44.924391

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2cbf5c81b941'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'aioutput',
        sa.Column('language', sa.JSON(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('encounter_id', sa.String(), nullable=False),
        sa.Column('type', sa.JSON(), nullable=False),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('model_version', sa.String(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_aioutput_content'), 'aioutput', ['content'], unique=False
    )
    op.create_index(
        op.f('ix_aioutput_encounter_id'),
        'aioutput',
        ['encounter_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_aioutput_language'), 'aioutput', ['language'], unique=False
    )
    op.create_index(
        op.f('ix_aioutput_model_version'),
        'aioutput',
        ['model_version'],
        unique=False,
    )
    op.create_index(
        op.f('ix_aioutput_timestamp'), 'aioutput', ['timestamp'], unique=False
    )
    op.create_index(
        op.f('ix_aioutput_type'), 'aioutput', ['type'], unique=False
    )
    op.create_table(
        'annotation',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('language', sa.JSON(), nullable=False),
        sa.Column('fhir_comments', sa.JSON(), nullable=True),
        sa.Column('extension', sa.JSON(), nullable=True),
        sa.Column('authorReference', sa.JSON(), nullable=True),
        sa.Column('authorString', sa.JSON(), nullable=True),
        sa.Column('authorString__ext', sa.JSON(), nullable=True),
        sa.Column('text', sa.JSON(), nullable=True),
        sa.Column('text__ext', sa.JSON(), nullable=True),
        sa.Column('time', sa.JSON(), nullable=True),
        sa.Column('time__ext', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_annotation_authorReference'),
        'annotation',
        ['authorReference'],
        unique=False,
    )
    op.create_index(
        op.f('ix_annotation_authorString'),
        'annotation',
        ['authorString'],
        unique=False,
    )
    op.create_index(
        op.f('ix_annotation_authorString__ext'),
        'annotation',
        ['authorString__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_annotation_extension'),
        'annotation',
        ['extension'],
        unique=False,
    )
    op.create_index(
        op.f('ix_annotation_fhir_comments'),
        'annotation',
        ['fhir_comments'],
        unique=False,
    )
    op.create_index(
        op.f('ix_annotation_language'),
        'annotation',
        ['language'],
        unique=False,
    )
    op.create_index(
        op.f('ix_annotation_text'), 'annotation', ['text'], unique=False
    )
    op.create_index(
        op.f('ix_annotation_text__ext'),
        'annotation',
        ['text__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_annotation_time'), 'annotation', ['time'], unique=False
    )
    op.create_index(
        op.f('ix_annotation_time__ext'),
        'annotation',
        ['time__ext'],
        unique=False,
    )
    op.create_table(
        'clinicalimpression',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('language', sa.JSON(), nullable=True),
        sa.Column('fhir_comments', sa.JSON(), nullable=True),
        sa.Column('implicitRules', sa.JSON(), nullable=True),
        sa.Column('implicitRules__ext', sa.JSON(), nullable=True),
        sa.Column('language__ext', sa.JSON(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.Column('contained', sa.JSON(), nullable=True),
        sa.Column('extension', sa.JSON(), nullable=True),
        sa.Column('modifierExtension', sa.JSON(), nullable=True),
        sa.Column('text', sa.JSON(), nullable=True),
        sa.Column('changePattern', sa.JSON(), nullable=True),
        sa.Column('date', sa.JSON(), nullable=True),
        sa.Column('date__ext', sa.JSON(), nullable=True),
        sa.Column('description', sa.JSON(), nullable=True),
        sa.Column('description__ext', sa.JSON(), nullable=True),
        sa.Column('effectiveDateTime', sa.JSON(), nullable=True),
        sa.Column('effectiveDateTime__ext', sa.JSON(), nullable=True),
        sa.Column('effectivePeriod', sa.JSON(), nullable=True),
        sa.Column('encounter', sa.JSON(), nullable=True),
        sa.Column('finding', sa.JSON(), nullable=True),
        sa.Column('identifier', sa.JSON(), nullable=True),
        sa.Column('note', sa.JSON(), nullable=True),
        sa.Column('performer', sa.JSON(), nullable=True),
        sa.Column('previous', sa.JSON(), nullable=True),
        sa.Column('problem', sa.JSON(), nullable=True),
        sa.Column('prognosisCodeableConcept', sa.JSON(), nullable=True),
        sa.Column('prognosisReference', sa.JSON(), nullable=True),
        sa.Column('protocol', sa.JSON(), nullable=True),
        sa.Column('protocol__ext', sa.JSON(), nullable=True),
        sa.Column('status', sa.JSON(), nullable=True),
        sa.Column('status__ext', sa.JSON(), nullable=True),
        sa.Column('statusReason', sa.JSON(), nullable=True),
        sa.Column('subject', sa.JSON(), nullable=False),
        sa.Column('summary', sa.JSON(), nullable=True),
        sa.Column('summary__ext', sa.JSON(), nullable=True),
        sa.Column('supportingInfo', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_clinicalimpression_changePattern'),
        'clinicalimpression',
        ['changePattern'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_contained'),
        'clinicalimpression',
        ['contained'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_date'),
        'clinicalimpression',
        ['date'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_date__ext'),
        'clinicalimpression',
        ['date__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_description'),
        'clinicalimpression',
        ['description'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_description__ext'),
        'clinicalimpression',
        ['description__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_effectiveDateTime'),
        'clinicalimpression',
        ['effectiveDateTime'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_effectiveDateTime__ext'),
        'clinicalimpression',
        ['effectiveDateTime__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_effectivePeriod'),
        'clinicalimpression',
        ['effectivePeriod'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_encounter'),
        'clinicalimpression',
        ['encounter'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_extension'),
        'clinicalimpression',
        ['extension'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_fhir_comments'),
        'clinicalimpression',
        ['fhir_comments'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_finding'),
        'clinicalimpression',
        ['finding'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_identifier'),
        'clinicalimpression',
        ['identifier'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_implicitRules'),
        'clinicalimpression',
        ['implicitRules'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_implicitRules__ext'),
        'clinicalimpression',
        ['implicitRules__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_language'),
        'clinicalimpression',
        ['language'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_language__ext'),
        'clinicalimpression',
        ['language__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_meta'),
        'clinicalimpression',
        ['meta'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_modifierExtension'),
        'clinicalimpression',
        ['modifierExtension'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_note'),
        'clinicalimpression',
        ['note'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_performer'),
        'clinicalimpression',
        ['performer'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_previous'),
        'clinicalimpression',
        ['previous'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_problem'),
        'clinicalimpression',
        ['problem'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_prognosisCodeableConcept'),
        'clinicalimpression',
        ['prognosisCodeableConcept'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_prognosisReference'),
        'clinicalimpression',
        ['prognosisReference'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_protocol'),
        'clinicalimpression',
        ['protocol'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_protocol__ext'),
        'clinicalimpression',
        ['protocol__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_status'),
        'clinicalimpression',
        ['status'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_statusReason'),
        'clinicalimpression',
        ['statusReason'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_status__ext'),
        'clinicalimpression',
        ['status__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_subject'),
        'clinicalimpression',
        ['subject'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_summary'),
        'clinicalimpression',
        ['summary'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_summary__ext'),
        'clinicalimpression',
        ['summary__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_supportingInfo'),
        'clinicalimpression',
        ['supportingInfo'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clinicalimpression_text'),
        'clinicalimpression',
        ['text'],
        unique=False,
    )
    op.create_table(
        'condition',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('language', sa.JSON(), nullable=True),
        sa.Column('fhir_comments', sa.JSON(), nullable=True),
        sa.Column('implicitRules', sa.JSON(), nullable=True),
        sa.Column('implicitRules__ext', sa.JSON(), nullable=True),
        sa.Column('language__ext', sa.JSON(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.Column('contained', sa.JSON(), nullable=True),
        sa.Column('extension', sa.JSON(), nullable=True),
        sa.Column('modifierExtension', sa.JSON(), nullable=True),
        sa.Column('text', sa.JSON(), nullable=True),
        sa.Column('abatementAge', sa.JSON(), nullable=True),
        sa.Column('abatementDateTime', sa.JSON(), nullable=True),
        sa.Column('abatementDateTime__ext', sa.JSON(), nullable=True),
        sa.Column('abatementPeriod', sa.JSON(), nullable=True),
        sa.Column('abatementRange', sa.JSON(), nullable=True),
        sa.Column('abatementString', sa.JSON(), nullable=True),
        sa.Column('abatementString__ext', sa.JSON(), nullable=True),
        sa.Column('bodySite', sa.JSON(), nullable=True),
        sa.Column('category', sa.JSON(), nullable=True),
        sa.Column('clinicalStatus', sa.JSON(), nullable=False),
        sa.Column('code', sa.JSON(), nullable=True),
        sa.Column('encounter', sa.JSON(), nullable=True),
        sa.Column('evidence', sa.JSON(), nullable=True),
        sa.Column('identifier', sa.JSON(), nullable=True),
        sa.Column('note', sa.JSON(), nullable=True),
        sa.Column('onsetAge', sa.JSON(), nullable=True),
        sa.Column('onsetDateTime', sa.JSON(), nullable=True),
        sa.Column('onsetDateTime__ext', sa.JSON(), nullable=True),
        sa.Column('onsetPeriod', sa.JSON(), nullable=True),
        sa.Column('onsetRange', sa.JSON(), nullable=True),
        sa.Column('onsetString', sa.JSON(), nullable=True),
        sa.Column('onsetString__ext', sa.JSON(), nullable=True),
        sa.Column('participant', sa.JSON(), nullable=True),
        sa.Column('recordedDate', sa.JSON(), nullable=True),
        sa.Column('recordedDate__ext', sa.JSON(), nullable=True),
        sa.Column('severity', sa.JSON(), nullable=True),
        sa.Column('stage', sa.JSON(), nullable=True),
        sa.Column('subject', sa.JSON(), nullable=False),
        sa.Column('verificationStatus', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_condition_abatementAge'),
        'condition',
        ['abatementAge'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_abatementDateTime'),
        'condition',
        ['abatementDateTime'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_abatementDateTime__ext'),
        'condition',
        ['abatementDateTime__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_abatementPeriod'),
        'condition',
        ['abatementPeriod'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_abatementRange'),
        'condition',
        ['abatementRange'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_abatementString'),
        'condition',
        ['abatementString'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_abatementString__ext'),
        'condition',
        ['abatementString__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_bodySite'), 'condition', ['bodySite'], unique=False
    )
    op.create_index(
        op.f('ix_condition_category'), 'condition', ['category'], unique=False
    )
    op.create_index(
        op.f('ix_condition_clinicalStatus'),
        'condition',
        ['clinicalStatus'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_code'), 'condition', ['code'], unique=False
    )
    op.create_index(
        op.f('ix_condition_contained'),
        'condition',
        ['contained'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_encounter'),
        'condition',
        ['encounter'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_evidence'), 'condition', ['evidence'], unique=False
    )
    op.create_index(
        op.f('ix_condition_extension'),
        'condition',
        ['extension'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_fhir_comments'),
        'condition',
        ['fhir_comments'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_identifier'),
        'condition',
        ['identifier'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_implicitRules'),
        'condition',
        ['implicitRules'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_implicitRules__ext'),
        'condition',
        ['implicitRules__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_language'), 'condition', ['language'], unique=False
    )
    op.create_index(
        op.f('ix_condition_language__ext'),
        'condition',
        ['language__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_meta'), 'condition', ['meta'], unique=False
    )
    op.create_index(
        op.f('ix_condition_modifierExtension'),
        'condition',
        ['modifierExtension'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_note'), 'condition', ['note'], unique=False
    )
    op.create_index(
        op.f('ix_condition_onsetAge'), 'condition', ['onsetAge'], unique=False
    )
    op.create_index(
        op.f('ix_condition_onsetDateTime'),
        'condition',
        ['onsetDateTime'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_onsetDateTime__ext'),
        'condition',
        ['onsetDateTime__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_onsetPeriod'),
        'condition',
        ['onsetPeriod'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_onsetRange'),
        'condition',
        ['onsetRange'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_onsetString'),
        'condition',
        ['onsetString'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_onsetString__ext'),
        'condition',
        ['onsetString__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_participant'),
        'condition',
        ['participant'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_recordedDate'),
        'condition',
        ['recordedDate'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_recordedDate__ext'),
        'condition',
        ['recordedDate__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_condition_severity'), 'condition', ['severity'], unique=False
    )
    op.create_index(
        op.f('ix_condition_stage'), 'condition', ['stage'], unique=False
    )
    op.create_index(
        op.f('ix_condition_subject'), 'condition', ['subject'], unique=False
    )
    op.create_index(
        op.f('ix_condition_text'), 'condition', ['text'], unique=False
    )
    op.create_index(
        op.f('ix_condition_verificationStatus'),
        'condition',
        ['verificationStatus'],
        unique=False,
    )
    op.create_table(
        'deidentifieddatasetdescriptor',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('language', sa.JSON(), nullable=False),
        sa.Column('dataset_id', sa.String(), nullable=False),
        sa.Column('generation_date', sa.DateTime(), nullable=False),
        sa.Column('version', sa.String(), nullable=False),
        sa.Column('records', sa.Integer(), nullable=False),
        sa.Column('license', sa.String(), nullable=False),
        sa.Column('url', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_deidentifieddatasetdescriptor_dataset_id'),
        'deidentifieddatasetdescriptor',
        ['dataset_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_deidentifieddatasetdescriptor_generation_date'),
        'deidentifieddatasetdescriptor',
        ['generation_date'],
        unique=False,
    )
    op.create_index(
        op.f('ix_deidentifieddatasetdescriptor_language'),
        'deidentifieddatasetdescriptor',
        ['language'],
        unique=False,
    )
    op.create_index(
        op.f('ix_deidentifieddatasetdescriptor_license'),
        'deidentifieddatasetdescriptor',
        ['license'],
        unique=False,
    )
    op.create_index(
        op.f('ix_deidentifieddatasetdescriptor_records'),
        'deidentifieddatasetdescriptor',
        ['records'],
        unique=False,
    )
    op.create_index(
        op.f('ix_deidentifieddatasetdescriptor_url'),
        'deidentifieddatasetdescriptor',
        ['url'],
        unique=False,
    )
    op.create_index(
        op.f('ix_deidentifieddatasetdescriptor_version'),
        'deidentifieddatasetdescriptor',
        ['version'],
        unique=False,
    )
    op.create_table(
        'diagnoses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'encounter',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('language', sa.JSON(), nullable=True),
        sa.Column('fhir_comments', sa.JSON(), nullable=True),
        sa.Column('implicitRules', sa.JSON(), nullable=True),
        sa.Column('implicitRules__ext', sa.JSON(), nullable=True),
        sa.Column('language__ext', sa.JSON(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.Column('contained', sa.JSON(), nullable=True),
        sa.Column('extension', sa.JSON(), nullable=True),
        sa.Column('modifierExtension', sa.JSON(), nullable=True),
        sa.Column('text', sa.JSON(), nullable=True),
        sa.Column('account', sa.JSON(), nullable=True),
        sa.Column('actualPeriod', sa.JSON(), nullable=True),
        sa.Column('admission', sa.JSON(), nullable=True),
        sa.Column('appointment', sa.JSON(), nullable=True),
        sa.Column('basedOn', sa.JSON(), nullable=True),
        sa.Column('careTeam', sa.JSON(), nullable=True),
        sa.Column('class_fhir', sa.JSON(), nullable=True),
        sa.Column('diagnosis', sa.JSON(), nullable=True),
        sa.Column('dietPreference', sa.JSON(), nullable=True),
        sa.Column('episodeOfCare', sa.JSON(), nullable=True),
        sa.Column('identifier', sa.JSON(), nullable=True),
        sa.Column('length', sa.JSON(), nullable=True),
        sa.Column('location', sa.JSON(), nullable=True),
        sa.Column('partOf', sa.JSON(), nullable=True),
        sa.Column('participant', sa.JSON(), nullable=True),
        sa.Column('plannedEndDate', sa.JSON(), nullable=True),
        sa.Column('plannedEndDate__ext', sa.JSON(), nullable=True),
        sa.Column('plannedStartDate', sa.JSON(), nullable=True),
        sa.Column('plannedStartDate__ext', sa.JSON(), nullable=True),
        sa.Column('priority', sa.JSON(), nullable=True),
        sa.Column('reason', sa.JSON(), nullable=True),
        sa.Column('serviceProvider', sa.JSON(), nullable=True),
        sa.Column('serviceType', sa.JSON(), nullable=True),
        sa.Column('specialArrangement', sa.JSON(), nullable=True),
        sa.Column('specialCourtesy', sa.JSON(), nullable=True),
        sa.Column('status', sa.JSON(), nullable=True),
        sa.Column('status__ext', sa.JSON(), nullable=True),
        sa.Column('subject', sa.JSON(), nullable=True),
        sa.Column('subjectStatus', sa.JSON(), nullable=True),
        sa.Column('type', sa.JSON(), nullable=True),
        sa.Column('virtualService', sa.JSON(), nullable=True),
        sa.Column('canonicalEpisodeId', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_encounter_account'), 'encounter', ['account'], unique=False
    )
    op.create_index(
        op.f('ix_encounter_actualPeriod'),
        'encounter',
        ['actualPeriod'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_admission'),
        'encounter',
        ['admission'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_appointment'),
        'encounter',
        ['appointment'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_basedOn'), 'encounter', ['basedOn'], unique=False
    )
    op.create_index(
        op.f('ix_encounter_canonicalEpisodeId'),
        'encounter',
        ['canonicalEpisodeId'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_careTeam'), 'encounter', ['careTeam'], unique=False
    )
    op.create_index(
        op.f('ix_encounter_class_fhir'),
        'encounter',
        ['class_fhir'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_contained'),
        'encounter',
        ['contained'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_diagnosis'),
        'encounter',
        ['diagnosis'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_dietPreference'),
        'encounter',
        ['dietPreference'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_episodeOfCare'),
        'encounter',
        ['episodeOfCare'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_extension'),
        'encounter',
        ['extension'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_fhir_comments'),
        'encounter',
        ['fhir_comments'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_identifier'),
        'encounter',
        ['identifier'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_implicitRules'),
        'encounter',
        ['implicitRules'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_implicitRules__ext'),
        'encounter',
        ['implicitRules__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_language'), 'encounter', ['language'], unique=False
    )
    op.create_index(
        op.f('ix_encounter_language__ext'),
        'encounter',
        ['language__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_length'), 'encounter', ['length'], unique=False
    )
    op.create_index(
        op.f('ix_encounter_location'), 'encounter', ['location'], unique=False
    )
    op.create_index(
        op.f('ix_encounter_meta'), 'encounter', ['meta'], unique=False
    )
    op.create_index(
        op.f('ix_encounter_modifierExtension'),
        'encounter',
        ['modifierExtension'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_partOf'), 'encounter', ['partOf'], unique=False
    )
    op.create_index(
        op.f('ix_encounter_participant'),
        'encounter',
        ['participant'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_plannedEndDate'),
        'encounter',
        ['plannedEndDate'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_plannedEndDate__ext'),
        'encounter',
        ['plannedEndDate__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_plannedStartDate'),
        'encounter',
        ['plannedStartDate'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_plannedStartDate__ext'),
        'encounter',
        ['plannedStartDate__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_priority'), 'encounter', ['priority'], unique=False
    )
    op.create_index(
        op.f('ix_encounter_reason'), 'encounter', ['reason'], unique=False
    )
    op.create_index(
        op.f('ix_encounter_serviceProvider'),
        'encounter',
        ['serviceProvider'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_serviceType'),
        'encounter',
        ['serviceType'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_specialArrangement'),
        'encounter',
        ['specialArrangement'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_specialCourtesy'),
        'encounter',
        ['specialCourtesy'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_status'), 'encounter', ['status'], unique=False
    )
    op.create_index(
        op.f('ix_encounter_status__ext'),
        'encounter',
        ['status__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_subject'), 'encounter', ['subject'], unique=False
    )
    op.create_index(
        op.f('ix_encounter_subjectStatus'),
        'encounter',
        ['subjectStatus'],
        unique=False,
    )
    op.create_index(
        op.f('ix_encounter_text'), 'encounter', ['text'], unique=False
    )
    op.create_index(
        op.f('ix_encounter_type'), 'encounter', ['type'], unique=False
    )
    op.create_index(
        op.f('ix_encounter_virtualService'),
        'encounter',
        ['virtualService'],
        unique=False,
    )
    op.create_table(
        'evaluation',
        sa.Column('language', sa.JSON(), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('aioutput_id', sa.String(), nullable=False),
        sa.Column('output_type', sa.JSON(), nullable=False),
        sa.Column('ratings', sa.JSON(), nullable=False),
        sa.Column('safety', sa.JSON(), nullable=False),
        sa.Column('comments', sa.JSON(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_evaluation_aioutput_id'),
        'evaluation',
        ['aioutput_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_evaluation_comments'),
        'evaluation',
        ['comments'],
        unique=False,
    )
    op.create_index(
        op.f('ix_evaluation_language'),
        'evaluation',
        ['language'],
        unique=False,
    )
    op.create_index(
        op.f('ix_evaluation_output_type'),
        'evaluation',
        ['output_type'],
        unique=False,
    )
    op.create_index(
        op.f('ix_evaluation_ratings'), 'evaluation', ['ratings'], unique=False
    )
    op.create_index(
        op.f('ix_evaluation_safety'), 'evaluation', ['safety'], unique=False
    )
    op.create_index(
        op.f('ix_evaluation_timestamp'),
        'evaluation',
        ['timestamp'],
        unique=False,
    )
    op.create_table(
        'exams',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'llmdiagnosis',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('summary', sa.String(), nullable=False),
        sa.Column('options', sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_llmdiagnosis_options'),
        'llmdiagnosis',
        ['options'],
        unique=False,
    )
    op.create_index(
        op.f('ix_llmdiagnosis_summary'),
        'llmdiagnosis',
        ['summary'],
        unique=False,
    )
    op.create_table(
        'observation',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('language', sa.JSON(), nullable=True),
        sa.Column('fhir_comments', sa.JSON(), nullable=True),
        sa.Column('implicitRules', sa.JSON(), nullable=True),
        sa.Column('implicitRules__ext', sa.JSON(), nullable=True),
        sa.Column('language__ext', sa.JSON(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.Column('contained', sa.JSON(), nullable=True),
        sa.Column('extension', sa.JSON(), nullable=True),
        sa.Column('modifierExtension', sa.JSON(), nullable=True),
        sa.Column('text', sa.JSON(), nullable=True),
        sa.Column('basedOn', sa.JSON(), nullable=True),
        sa.Column('bodySite', sa.JSON(), nullable=True),
        sa.Column('bodyStructure', sa.JSON(), nullable=True),
        sa.Column('category', sa.JSON(), nullable=True),
        sa.Column('code', sa.JSON(), nullable=False),
        sa.Column('component', sa.JSON(), nullable=True),
        sa.Column('dataAbsentReason', sa.JSON(), nullable=True),
        sa.Column('derivedFrom', sa.JSON(), nullable=True),
        sa.Column('device', sa.JSON(), nullable=True),
        sa.Column('effectiveDateTime', sa.JSON(), nullable=True),
        sa.Column('effectiveDateTime__ext', sa.JSON(), nullable=True),
        sa.Column('effectiveInstant', sa.JSON(), nullable=True),
        sa.Column('effectiveInstant__ext', sa.JSON(), nullable=True),
        sa.Column('effectivePeriod', sa.JSON(), nullable=True),
        sa.Column('effectiveTiming', sa.JSON(), nullable=True),
        sa.Column('encounter', sa.JSON(), nullable=True),
        sa.Column('focus', sa.JSON(), nullable=True),
        sa.Column('hasMember', sa.JSON(), nullable=True),
        sa.Column('identifier', sa.JSON(), nullable=True),
        sa.Column('instantiatesCanonical', sa.JSON(), nullable=True),
        sa.Column('instantiatesCanonical__ext', sa.JSON(), nullable=True),
        sa.Column('instantiatesReference', sa.JSON(), nullable=True),
        sa.Column('interpretation', sa.JSON(), nullable=True),
        sa.Column('issued', sa.JSON(), nullable=True),
        sa.Column('issued__ext', sa.JSON(), nullable=True),
        sa.Column('method', sa.JSON(), nullable=True),
        sa.Column('note', sa.JSON(), nullable=True),
        sa.Column('partOf', sa.JSON(), nullable=True),
        sa.Column('performer', sa.JSON(), nullable=True),
        sa.Column('referenceRange', sa.JSON(), nullable=True),
        sa.Column('specimen', sa.JSON(), nullable=True),
        sa.Column('status', sa.JSON(), nullable=True),
        sa.Column('status__ext', sa.JSON(), nullable=True),
        sa.Column('subject', sa.JSON(), nullable=True),
        sa.Column('triggeredBy', sa.JSON(), nullable=True),
        sa.Column('valueAttachment', sa.JSON(), nullable=True),
        sa.Column('valueBoolean', sa.JSON(), nullable=True),
        sa.Column('valueBoolean__ext', sa.JSON(), nullable=True),
        sa.Column('valueCodeableConcept', sa.JSON(), nullable=True),
        sa.Column('valueDateTime', sa.JSON(), nullable=True),
        sa.Column('valueDateTime__ext', sa.JSON(), nullable=True),
        sa.Column('valueInteger', sa.JSON(), nullable=True),
        sa.Column('valueInteger__ext', sa.JSON(), nullable=True),
        sa.Column('valuePeriod', sa.JSON(), nullable=True),
        sa.Column('valueQuantity', sa.JSON(), nullable=True),
        sa.Column('valueRange', sa.JSON(), nullable=True),
        sa.Column('valueRatio', sa.JSON(), nullable=True),
        sa.Column('valueReference', sa.JSON(), nullable=True),
        sa.Column('valueSampledData', sa.JSON(), nullable=True),
        sa.Column('valueString', sa.JSON(), nullable=True),
        sa.Column('valueString__ext', sa.JSON(), nullable=True),
        sa.Column('valueTime', sa.JSON(), nullable=True),
        sa.Column('valueTime__ext', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_observation_basedOn'),
        'observation',
        ['basedOn'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_bodySite'),
        'observation',
        ['bodySite'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_bodyStructure'),
        'observation',
        ['bodyStructure'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_category'),
        'observation',
        ['category'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_code'), 'observation', ['code'], unique=False
    )
    op.create_index(
        op.f('ix_observation_component'),
        'observation',
        ['component'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_contained'),
        'observation',
        ['contained'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_dataAbsentReason'),
        'observation',
        ['dataAbsentReason'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_derivedFrom'),
        'observation',
        ['derivedFrom'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_device'), 'observation', ['device'], unique=False
    )
    op.create_index(
        op.f('ix_observation_effectiveDateTime'),
        'observation',
        ['effectiveDateTime'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_effectiveDateTime__ext'),
        'observation',
        ['effectiveDateTime__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_effectiveInstant'),
        'observation',
        ['effectiveInstant'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_effectiveInstant__ext'),
        'observation',
        ['effectiveInstant__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_effectivePeriod'),
        'observation',
        ['effectivePeriod'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_effectiveTiming'),
        'observation',
        ['effectiveTiming'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_encounter'),
        'observation',
        ['encounter'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_extension'),
        'observation',
        ['extension'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_fhir_comments'),
        'observation',
        ['fhir_comments'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_focus'), 'observation', ['focus'], unique=False
    )
    op.create_index(
        op.f('ix_observation_hasMember'),
        'observation',
        ['hasMember'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_identifier'),
        'observation',
        ['identifier'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_implicitRules'),
        'observation',
        ['implicitRules'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_implicitRules__ext'),
        'observation',
        ['implicitRules__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_instantiatesCanonical'),
        'observation',
        ['instantiatesCanonical'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_instantiatesCanonical__ext'),
        'observation',
        ['instantiatesCanonical__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_instantiatesReference'),
        'observation',
        ['instantiatesReference'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_interpretation'),
        'observation',
        ['interpretation'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_issued'), 'observation', ['issued'], unique=False
    )
    op.create_index(
        op.f('ix_observation_issued__ext'),
        'observation',
        ['issued__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_language'),
        'observation',
        ['language'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_language__ext'),
        'observation',
        ['language__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_meta'), 'observation', ['meta'], unique=False
    )
    op.create_index(
        op.f('ix_observation_method'), 'observation', ['method'], unique=False
    )
    op.create_index(
        op.f('ix_observation_modifierExtension'),
        'observation',
        ['modifierExtension'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_note'), 'observation', ['note'], unique=False
    )
    op.create_index(
        op.f('ix_observation_partOf'), 'observation', ['partOf'], unique=False
    )
    op.create_index(
        op.f('ix_observation_performer'),
        'observation',
        ['performer'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_referenceRange'),
        'observation',
        ['referenceRange'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_specimen'),
        'observation',
        ['specimen'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_status'), 'observation', ['status'], unique=False
    )
    op.create_index(
        op.f('ix_observation_status__ext'),
        'observation',
        ['status__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_subject'),
        'observation',
        ['subject'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_text'), 'observation', ['text'], unique=False
    )
    op.create_index(
        op.f('ix_observation_triggeredBy'),
        'observation',
        ['triggeredBy'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_valueAttachment'),
        'observation',
        ['valueAttachment'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_valueBoolean'),
        'observation',
        ['valueBoolean'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_valueBoolean__ext'),
        'observation',
        ['valueBoolean__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_valueCodeableConcept'),
        'observation',
        ['valueCodeableConcept'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_valueDateTime'),
        'observation',
        ['valueDateTime'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_valueDateTime__ext'),
        'observation',
        ['valueDateTime__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_valueInteger'),
        'observation',
        ['valueInteger'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_valueInteger__ext'),
        'observation',
        ['valueInteger__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_valuePeriod'),
        'observation',
        ['valuePeriod'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_valueQuantity'),
        'observation',
        ['valueQuantity'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_valueRange'),
        'observation',
        ['valueRange'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_valueRatio'),
        'observation',
        ['valueRatio'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_valueReference'),
        'observation',
        ['valueReference'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_valueSampledData'),
        'observation',
        ['valueSampledData'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_valueString'),
        'observation',
        ['valueString'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_valueString__ext'),
        'observation',
        ['valueString__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_valueTime'),
        'observation',
        ['valueTime'],
        unique=False,
    )
    op.create_index(
        op.f('ix_observation_valueTime__ext'),
        'observation',
        ['valueTime__ext'],
        unique=False,
    )
    op.create_table(
        'patient',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('language', sa.JSON(), nullable=True),
        sa.Column('fhir_comments', sa.JSON(), nullable=True),
        sa.Column('implicitRules', sa.JSON(), nullable=True),
        sa.Column('implicitRules__ext', sa.JSON(), nullable=True),
        sa.Column('language__ext', sa.JSON(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.Column('contained', sa.JSON(), nullable=True),
        sa.Column('extension', sa.JSON(), nullable=True),
        sa.Column('modifierExtension', sa.JSON(), nullable=True),
        sa.Column('text', sa.JSON(), nullable=True),
        sa.Column('active', sa.JSON(), nullable=True),
        sa.Column('active__ext', sa.JSON(), nullable=True),
        sa.Column('address', sa.JSON(), nullable=True),
        sa.Column('birthDate', sa.JSON(), nullable=True),
        sa.Column('birthDate__ext', sa.JSON(), nullable=True),
        sa.Column('communication', sa.JSON(), nullable=True),
        sa.Column('contact', sa.JSON(), nullable=True),
        sa.Column('deceasedBoolean', sa.JSON(), nullable=True),
        sa.Column('deceasedBoolean__ext', sa.JSON(), nullable=True),
        sa.Column('deceasedDateTime', sa.JSON(), nullable=True),
        sa.Column('deceasedDateTime__ext', sa.JSON(), nullable=True),
        sa.Column('gender', sa.JSON(), nullable=True),
        sa.Column('gender__ext', sa.JSON(), nullable=True),
        sa.Column('generalPractitioner', sa.JSON(), nullable=True),
        sa.Column('identifier', sa.JSON(), nullable=True),
        sa.Column('link', sa.JSON(), nullable=True),
        sa.Column('managingOrganization', sa.JSON(), nullable=True),
        sa.Column('maritalStatus', sa.JSON(), nullable=True),
        sa.Column('multipleBirthBoolean', sa.JSON(), nullable=True),
        sa.Column('multipleBirthBoolean__ext', sa.JSON(), nullable=True),
        sa.Column('multipleBirthInteger', sa.JSON(), nullable=True),
        sa.Column('multipleBirthInteger__ext', sa.JSON(), nullable=True),
        sa.Column('name', sa.JSON(), nullable=True),
        sa.Column('photo', sa.JSON(), nullable=True),
        sa.Column('telecom', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_patient_active'), 'patient', ['active'], unique=False
    )
    op.create_index(
        op.f('ix_patient_active__ext'),
        'patient',
        ['active__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_address'), 'patient', ['address'], unique=False
    )
    op.create_index(
        op.f('ix_patient_birthDate'), 'patient', ['birthDate'], unique=False
    )
    op.create_index(
        op.f('ix_patient_birthDate__ext'),
        'patient',
        ['birthDate__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_communication'),
        'patient',
        ['communication'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_contact'), 'patient', ['contact'], unique=False
    )
    op.create_index(
        op.f('ix_patient_contained'), 'patient', ['contained'], unique=False
    )
    op.create_index(
        op.f('ix_patient_deceasedBoolean'),
        'patient',
        ['deceasedBoolean'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_deceasedBoolean__ext'),
        'patient',
        ['deceasedBoolean__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_deceasedDateTime'),
        'patient',
        ['deceasedDateTime'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_deceasedDateTime__ext'),
        'patient',
        ['deceasedDateTime__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_extension'), 'patient', ['extension'], unique=False
    )
    op.create_index(
        op.f('ix_patient_fhir_comments'),
        'patient',
        ['fhir_comments'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_gender'), 'patient', ['gender'], unique=False
    )
    op.create_index(
        op.f('ix_patient_gender__ext'),
        'patient',
        ['gender__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_generalPractitioner'),
        'patient',
        ['generalPractitioner'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_identifier'), 'patient', ['identifier'], unique=False
    )
    op.create_index(
        op.f('ix_patient_implicitRules'),
        'patient',
        ['implicitRules'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_implicitRules__ext'),
        'patient',
        ['implicitRules__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_language'), 'patient', ['language'], unique=False
    )
    op.create_index(
        op.f('ix_patient_language__ext'),
        'patient',
        ['language__ext'],
        unique=False,
    )
    op.create_index(op.f('ix_patient_link'), 'patient', ['link'], unique=False)
    op.create_index(
        op.f('ix_patient_managingOrganization'),
        'patient',
        ['managingOrganization'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_maritalStatus'),
        'patient',
        ['maritalStatus'],
        unique=False,
    )
    op.create_index(op.f('ix_patient_meta'), 'patient', ['meta'], unique=False)
    op.create_index(
        op.f('ix_patient_modifierExtension'),
        'patient',
        ['modifierExtension'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_multipleBirthBoolean'),
        'patient',
        ['multipleBirthBoolean'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_multipleBirthBoolean__ext'),
        'patient',
        ['multipleBirthBoolean__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_multipleBirthInteger'),
        'patient',
        ['multipleBirthInteger'],
        unique=False,
    )
    op.create_index(
        op.f('ix_patient_multipleBirthInteger__ext'),
        'patient',
        ['multipleBirthInteger__ext'],
        unique=False,
    )
    op.create_index(op.f('ix_patient_name'), 'patient', ['name'], unique=False)
    op.create_index(
        op.f('ix_patient_photo'), 'patient', ['photo'], unique=False
    )
    op.create_index(
        op.f('ix_patient_telecom'), 'patient', ['telecom'], unique=False
    )
    op.create_index(op.f('ix_patient_text'), 'patient', ['text'], unique=False)
    op.create_table(
        'patients',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uuid', sa.String(length=36), nullable=False),
        sa.Column('age', sa.Integer(), nullable=True),
        sa.Column('gender', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_patients_uuid'), 'patients', ['uuid'], unique=True
    )
    op.create_table(
        'procedure',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('language', sa.JSON(), nullable=True),
        sa.Column('fhir_comments', sa.JSON(), nullable=True),
        sa.Column('implicitRules', sa.JSON(), nullable=True),
        sa.Column('implicitRules__ext', sa.JSON(), nullable=True),
        sa.Column('language__ext', sa.JSON(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.Column('contained', sa.JSON(), nullable=True),
        sa.Column('extension', sa.JSON(), nullable=True),
        sa.Column('modifierExtension', sa.JSON(), nullable=True),
        sa.Column('text', sa.JSON(), nullable=True),
        sa.Column('basedOn', sa.JSON(), nullable=True),
        sa.Column('bodySite', sa.JSON(), nullable=True),
        sa.Column('category', sa.JSON(), nullable=True),
        sa.Column('code', sa.JSON(), nullable=True),
        sa.Column('complication', sa.JSON(), nullable=True),
        sa.Column('encounter', sa.JSON(), nullable=True),
        sa.Column('focalDevice', sa.JSON(), nullable=True),
        sa.Column('focus', sa.JSON(), nullable=True),
        sa.Column('followUp', sa.JSON(), nullable=True),
        sa.Column('identifier', sa.JSON(), nullable=True),
        sa.Column('instantiatesCanonical', sa.JSON(), nullable=True),
        sa.Column('instantiatesCanonical__ext', sa.JSON(), nullable=True),
        sa.Column('instantiatesUri', sa.JSON(), nullable=True),
        sa.Column('instantiatesUri__ext', sa.JSON(), nullable=True),
        sa.Column('location', sa.JSON(), nullable=True),
        sa.Column('note', sa.JSON(), nullable=True),
        sa.Column('occurrenceAge', sa.JSON(), nullable=True),
        sa.Column('occurrenceDateTime', sa.JSON(), nullable=True),
        sa.Column('occurrenceDateTime__ext', sa.JSON(), nullable=True),
        sa.Column('occurrencePeriod', sa.JSON(), nullable=True),
        sa.Column('occurrenceRange', sa.JSON(), nullable=True),
        sa.Column('occurrenceString', sa.JSON(), nullable=True),
        sa.Column('occurrenceString__ext', sa.JSON(), nullable=True),
        sa.Column('occurrenceTiming', sa.JSON(), nullable=True),
        sa.Column('outcome', sa.JSON(), nullable=True),
        sa.Column('partOf', sa.JSON(), nullable=True),
        sa.Column('performer', sa.JSON(), nullable=True),
        sa.Column('reason', sa.JSON(), nullable=True),
        sa.Column('recorded', sa.JSON(), nullable=True),
        sa.Column('recorded__ext', sa.JSON(), nullable=True),
        sa.Column('recorder', sa.JSON(), nullable=True),
        sa.Column('report', sa.JSON(), nullable=True),
        sa.Column('reportedBoolean', sa.JSON(), nullable=True),
        sa.Column('reportedBoolean__ext', sa.JSON(), nullable=True),
        sa.Column('reportedReference', sa.JSON(), nullable=True),
        sa.Column('status', sa.JSON(), nullable=True),
        sa.Column('status__ext', sa.JSON(), nullable=True),
        sa.Column('statusReason', sa.JSON(), nullable=True),
        sa.Column('subject', sa.JSON(), nullable=False),
        sa.Column('supportingInfo', sa.JSON(), nullable=True),
        sa.Column('used', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_procedure_basedOn'), 'procedure', ['basedOn'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_bodySite'), 'procedure', ['bodySite'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_category'), 'procedure', ['category'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_code'), 'procedure', ['code'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_complication'),
        'procedure',
        ['complication'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_contained'),
        'procedure',
        ['contained'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_encounter'),
        'procedure',
        ['encounter'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_extension'),
        'procedure',
        ['extension'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_fhir_comments'),
        'procedure',
        ['fhir_comments'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_focalDevice'),
        'procedure',
        ['focalDevice'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_focus'), 'procedure', ['focus'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_followUp'), 'procedure', ['followUp'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_identifier'),
        'procedure',
        ['identifier'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_implicitRules'),
        'procedure',
        ['implicitRules'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_implicitRules__ext'),
        'procedure',
        ['implicitRules__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_instantiatesCanonical'),
        'procedure',
        ['instantiatesCanonical'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_instantiatesCanonical__ext'),
        'procedure',
        ['instantiatesCanonical__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_instantiatesUri'),
        'procedure',
        ['instantiatesUri'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_instantiatesUri__ext'),
        'procedure',
        ['instantiatesUri__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_language'), 'procedure', ['language'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_language__ext'),
        'procedure',
        ['language__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_location'), 'procedure', ['location'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_meta'), 'procedure', ['meta'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_modifierExtension'),
        'procedure',
        ['modifierExtension'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_note'), 'procedure', ['note'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_occurrenceAge'),
        'procedure',
        ['occurrenceAge'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_occurrenceDateTime'),
        'procedure',
        ['occurrenceDateTime'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_occurrenceDateTime__ext'),
        'procedure',
        ['occurrenceDateTime__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_occurrencePeriod'),
        'procedure',
        ['occurrencePeriod'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_occurrenceRange'),
        'procedure',
        ['occurrenceRange'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_occurrenceString'),
        'procedure',
        ['occurrenceString'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_occurrenceString__ext'),
        'procedure',
        ['occurrenceString__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_occurrenceTiming'),
        'procedure',
        ['occurrenceTiming'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_outcome'), 'procedure', ['outcome'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_partOf'), 'procedure', ['partOf'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_performer'),
        'procedure',
        ['performer'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_reason'), 'procedure', ['reason'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_recorded'), 'procedure', ['recorded'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_recorded__ext'),
        'procedure',
        ['recorded__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_recorder'), 'procedure', ['recorder'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_report'), 'procedure', ['report'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_reportedBoolean'),
        'procedure',
        ['reportedBoolean'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_reportedBoolean__ext'),
        'procedure',
        ['reportedBoolean__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_reportedReference'),
        'procedure',
        ['reportedReference'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_status'), 'procedure', ['status'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_statusReason'),
        'procedure',
        ['statusReason'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_status__ext'),
        'procedure',
        ['status__ext'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_subject'), 'procedure', ['subject'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_supportingInfo'),
        'procedure',
        ['supportingInfo'],
        unique=False,
    )
    op.create_index(
        op.f('ix_procedure_text'), 'procedure', ['text'], unique=False
    )
    op.create_index(
        op.f('ix_procedure_used'), 'procedure', ['used'], unique=False
    )
    op.create_table(
        'consultations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('lang', sa.String(length=10), nullable=True),
        sa.Column('weight_kg', sa.Float(), nullable=True),
        sa.Column('height_cm', sa.Float(), nullable=True),
        sa.Column('diet', sa.Text(), nullable=True),
        sa.Column('sleep_hours', sa.Float(), nullable=True),
        sa.Column('physical_activity', sa.Text(), nullable=True),
        sa.Column('mental_exercises', sa.Text(), nullable=True),
        sa.Column('symptoms', sa.Text(), nullable=True),
        sa.Column('mental_health', sa.Text(), nullable=True),
        sa.Column('previous_tests', sa.Text(), nullable=True),
        sa.Column('wearable_data', sa.JSON(), nullable=True),
        sa.Column('ai_diag_raw', sa.JSON(), nullable=True),
        sa.Column('ai_exam_raw', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ['patient_id'],
            ['patients.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'consultation_diagnoses',
        sa.Column('consultation_id', sa.Integer(), nullable=False),
        sa.Column('diagnosis_id', sa.Integer(), nullable=False),
        sa.Column('accuracy', sa.Integer(), nullable=True),
        sa.Column('relevance', sa.Integer(), nullable=True),
        sa.Column('usefulness', sa.Integer(), nullable=True),
        sa.Column('coherence', sa.Integer(), nullable=True),
        sa.Column('comments', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['consultation_id'],
            ['consultations.id'],
        ),
        sa.ForeignKeyConstraint(
            ['diagnosis_id'],
            ['diagnoses.id'],
        ),
        sa.PrimaryKeyConstraint('consultation_id', 'diagnosis_id'),
    )
    op.create_table(
        'consultation_exams',
        sa.Column('consultation_id', sa.Integer(), nullable=False),
        sa.Column('exam_id', sa.Integer(), nullable=False),
        sa.Column('accuracy', sa.Integer(), nullable=True),
        sa.Column('relevance', sa.Integer(), nullable=True),
        sa.Column('usefulness', sa.Integer(), nullable=True),
        sa.Column('coherence', sa.Integer(), nullable=True),
        sa.Column('safety', sa.String(length=50), nullable=True),
        sa.Column('comments', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['consultation_id'],
            ['consultations.id'],
        ),
        sa.ForeignKeyConstraint(
            ['exam_id'],
            ['exams.id'],
        ),
        sa.PrimaryKeyConstraint('consultation_id', 'exam_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultation_exams')
    op.drop_table('consultation_diagnoses')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_procedure_used'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_text'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_supportingInfo'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_subject'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_status__ext'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_statusReason'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_status'), table_name='procedure')
    op.drop_index(
        op.f('ix_procedure_reportedReference'), table_name='procedure'
    )
    op.drop_index(
        op.f('ix_procedure_reportedBoolean__ext'), table_name='procedure'
    )
    op.drop_index(op.f('ix_procedure_reportedBoolean'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_report'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_recorder'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_recorded__ext'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_recorded'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_reason'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_performer'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_partOf'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_outcome'), table_name='procedure')
    op.drop_index(
        op.f('ix_procedure_occurrenceTiming'), table_name='procedure'
    )
    op.drop_index(
        op.f('ix_procedure_occurrenceString__ext'), table_name='procedure'
    )
    op.drop_index(
        op.f('ix_procedure_occurrenceString'), table_name='procedure'
    )
    op.drop_index(op.f('ix_procedure_occurrenceRange'), table_name='procedure')
    op.drop_index(
        op.f('ix_procedure_occurrencePeriod'), table_name='procedure'
    )
    op.drop_index(
        op.f('ix_procedure_occurrenceDateTime__ext'), table_name='procedure'
    )
    op.drop_index(
        op.f('ix_procedure_occurrenceDateTime'), table_name='procedure'
    )
    op.drop_index(op.f('ix_procedure_occurrenceAge'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_note'), table_name='procedure')
    op.drop_index(
        op.f('ix_procedure_modifierExtension'), table_name='procedure'
    )
    op.drop_index(op.f('ix_procedure_meta'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_location'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_language__ext'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_language'), table_name='procedure')
    op.drop_index(
        op.f('ix_procedure_instantiatesUri__ext'), table_name='procedure'
    )
    op.drop_index(op.f('ix_procedure_instantiatesUri'), table_name='procedure')
    op.drop_index(
        op.f('ix_procedure_instantiatesCanonical__ext'), table_name='procedure'
    )
    op.drop_index(
        op.f('ix_procedure_instantiatesCanonical'), table_name='procedure'
    )
    op.drop_index(
        op.f('ix_procedure_implicitRules__ext'), table_name='procedure'
    )
    op.drop_index(op.f('ix_procedure_implicitRules'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_identifier'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_followUp'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_focus'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_focalDevice'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_fhir_comments'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_extension'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_encounter'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_contained'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_complication'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_code'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_category'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_bodySite'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_basedOn'), table_name='procedure')
    op.drop_table('procedure')
    op.drop_index(op.f('ix_patients_uuid'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_patient_text'), table_name='patient')
    op.drop_index(op.f('ix_patient_telecom'), table_name='patient')
    op.drop_index(op.f('ix_patient_photo'), table_name='patient')
    op.drop_index(op.f('ix_patient_name'), table_name='patient')
    op.drop_index(
        op.f('ix_patient_multipleBirthInteger__ext'), table_name='patient'
    )
    op.drop_index(
        op.f('ix_patient_multipleBirthInteger'), table_name='patient'
    )
    op.drop_index(
        op.f('ix_patient_multipleBirthBoolean__ext'), table_name='patient'
    )
    op.drop_index(
        op.f('ix_patient_multipleBirthBoolean'), table_name='patient'
    )
    op.drop_index(op.f('ix_patient_modifierExtension'), table_name='patient')
    op.drop_index(op.f('ix_patient_meta'), table_name='patient')
    op.drop_index(op.f('ix_patient_maritalStatus'), table_name='patient')
    op.drop_index(
        op.f('ix_patient_managingOrganization'), table_name='patient'
    )
    op.drop_index(op.f('ix_patient_link'), table_name='patient')
    op.drop_index(op.f('ix_patient_language__ext'), table_name='patient')
    op.drop_index(op.f('ix_patient_language'), table_name='patient')
    op.drop_index(op.f('ix_patient_implicitRules__ext'), table_name='patient')
    op.drop_index(op.f('ix_patient_implicitRules'), table_name='patient')
    op.drop_index(op.f('ix_patient_identifier'), table_name='patient')
    op.drop_index(op.f('ix_patient_generalPractitioner'), table_name='patient')
    op.drop_index(op.f('ix_patient_gender__ext'), table_name='patient')
    op.drop_index(op.f('ix_patient_gender'), table_name='patient')
    op.drop_index(op.f('ix_patient_fhir_comments'), table_name='patient')
    op.drop_index(op.f('ix_patient_extension'), table_name='patient')
    op.drop_index(
        op.f('ix_patient_deceasedDateTime__ext'), table_name='patient'
    )
    op.drop_index(op.f('ix_patient_deceasedDateTime'), table_name='patient')
    op.drop_index(
        op.f('ix_patient_deceasedBoolean__ext'), table_name='patient'
    )
    op.drop_index(op.f('ix_patient_deceasedBoolean'), table_name='patient')
    op.drop_index(op.f('ix_patient_contained'), table_name='patient')
    op.drop_index(op.f('ix_patient_contact'), table_name='patient')
    op.drop_index(op.f('ix_patient_communication'), table_name='patient')
    op.drop_index(op.f('ix_patient_birthDate__ext'), table_name='patient')
    op.drop_index(op.f('ix_patient_birthDate'), table_name='patient')
    op.drop_index(op.f('ix_patient_address'), table_name='patient')
    op.drop_index(op.f('ix_patient_active__ext'), table_name='patient')
    op.drop_index(op.f('ix_patient_active'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(
        op.f('ix_observation_valueTime__ext'), table_name='observation'
    )
    op.drop_index(op.f('ix_observation_valueTime'), table_name='observation')
    op.drop_index(
        op.f('ix_observation_valueString__ext'), table_name='observation'
    )
    op.drop_index(op.f('ix_observation_valueString'), table_name='observation')
    op.drop_index(
        op.f('ix_observation_valueSampledData'), table_name='observation'
    )
    op.drop_index(
        op.f('ix_observation_valueReference'), table_name='observation'
    )
    op.drop_index(op.f('ix_observation_valueRatio'), table_name='observation')
    op.drop_index(op.f('ix_observation_valueRange'), table_name='observation')
    op.drop_index(
        op.f('ix_observation_valueQuantity'), table_name='observation'
    )
    op.drop_index(op.f('ix_observation_valuePeriod'), table_name='observation')
    op.drop_index(
        op.f('ix_observation_valueInteger__ext'), table_name='observation'
    )
    op.drop_index(
        op.f('ix_observation_valueInteger'), table_name='observation'
    )
    op.drop_index(
        op.f('ix_observation_valueDateTime__ext'), table_name='observation'
    )
    op.drop_index(
        op.f('ix_observation_valueDateTime'), table_name='observation'
    )
    op.drop_index(
        op.f('ix_observation_valueCodeableConcept'), table_name='observation'
    )
    op.drop_index(
        op.f('ix_observation_valueBoolean__ext'), table_name='observation'
    )
    op.drop_index(
        op.f('ix_observation_valueBoolean'), table_name='observation'
    )
    op.drop_index(
        op.f('ix_observation_valueAttachment'), table_name='observation'
    )
    op.drop_index(op.f('ix_observation_triggeredBy'), table_name='observation')
    op.drop_index(op.f('ix_observation_text'), table_name='observation')
    op.drop_index(op.f('ix_observation_subject'), table_name='observation')
    op.drop_index(op.f('ix_observation_status__ext'), table_name='observation')
    op.drop_index(op.f('ix_observation_status'), table_name='observation')
    op.drop_index(op.f('ix_observation_specimen'), table_name='observation')
    op.drop_index(
        op.f('ix_observation_referenceRange'), table_name='observation'
    )
    op.drop_index(op.f('ix_observation_performer'), table_name='observation')
    op.drop_index(op.f('ix_observation_partOf'), table_name='observation')
    op.drop_index(op.f('ix_observation_note'), table_name='observation')
    op.drop_index(
        op.f('ix_observation_modifierExtension'), table_name='observation'
    )
    op.drop_index(op.f('ix_observation_method'), table_name='observation')
    op.drop_index(op.f('ix_observation_meta'), table_name='observation')
    op.drop_index(
        op.f('ix_observation_language__ext'), table_name='observation'
    )
    op.drop_index(op.f('ix_observation_language'), table_name='observation')
    op.drop_index(op.f('ix_observation_issued__ext'), table_name='observation')
    op.drop_index(op.f('ix_observation_issued'), table_name='observation')
    op.drop_index(
        op.f('ix_observation_interpretation'), table_name='observation'
    )
    op.drop_index(
        op.f('ix_observation_instantiatesReference'), table_name='observation'
    )
    op.drop_index(
        op.f('ix_observation_instantiatesCanonical__ext'),
        table_name='observation',
    )
    op.drop_index(
        op.f('ix_observation_instantiatesCanonical'), table_name='observation'
    )
    op.drop_index(
        op.f('ix_observation_implicitRules__ext'), table_name='observation'
    )
    op.drop_index(
        op.f('ix_observation_implicitRules'), table_name='observation'
    )
    op.drop_index(op.f('ix_observation_identifier'), table_name='observation')
    op.drop_index(op.f('ix_observation_hasMember'), table_name='observation')
    op.drop_index(op.f('ix_observation_focus'), table_name='observation')
    op.drop_index(
        op.f('ix_observation_fhir_comments'), table_name='observation'
    )
    op.drop_index(op.f('ix_observation_extension'), table_name='observation')
    op.drop_index(op.f('ix_observation_encounter'), table_name='observation')
    op.drop_index(
        op.f('ix_observation_effectiveTiming'), table_name='observation'
    )
    op.drop_index(
        op.f('ix_observation_effectivePeriod'), table_name='observation'
    )
    op.drop_index(
        op.f('ix_observation_effectiveInstant__ext'), table_name='observation'
    )
    op.drop_index(
        op.f('ix_observation_effectiveInstant'), table_name='observation'
    )
    op.drop_index(
        op.f('ix_observation_effectiveDateTime__ext'), table_name='observation'
    )
    op.drop_index(
        op.f('ix_observation_effectiveDateTime'), table_name='observation'
    )
    op.drop_index(op.f('ix_observation_device'), table_name='observation')
    op.drop_index(op.f('ix_observation_derivedFrom'), table_name='observation')
    op.drop_index(
        op.f('ix_observation_dataAbsentReason'), table_name='observation'
    )
    op.drop_index(op.f('ix_observation_contained'), table_name='observation')
    op.drop_index(op.f('ix_observation_component'), table_name='observation')
    op.drop_index(op.f('ix_observation_code'), table_name='observation')
    op.drop_index(op.f('ix_observation_category'), table_name='observation')
    op.drop_index(
        op.f('ix_observation_bodyStructure'), table_name='observation'
    )
    op.drop_index(op.f('ix_observation_bodySite'), table_name='observation')
    op.drop_index(op.f('ix_observation_basedOn'), table_name='observation')
    op.drop_table('observation')
    op.drop_index(op.f('ix_llmdiagnosis_summary'), table_name='llmdiagnosis')
    op.drop_index(op.f('ix_llmdiagnosis_options'), table_name='llmdiagnosis')
    op.drop_table('llmdiagnosis')
    op.drop_table('exams')
    op.drop_index(op.f('ix_evaluation_timestamp'), table_name='evaluation')
    op.drop_index(op.f('ix_evaluation_safety'), table_name='evaluation')
    op.drop_index(op.f('ix_evaluation_ratings'), table_name='evaluation')
    op.drop_index(op.f('ix_evaluation_output_type'), table_name='evaluation')
    op.drop_index(op.f('ix_evaluation_language'), table_name='evaluation')
    op.drop_index(op.f('ix_evaluation_comments'), table_name='evaluation')
    op.drop_index(op.f('ix_evaluation_aioutput_id'), table_name='evaluation')
    op.drop_table('evaluation')
    op.drop_index(op.f('ix_encounter_virtualService'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_type'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_text'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_subjectStatus'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_subject'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_status__ext'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_status'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_specialCourtesy'), table_name='encounter')
    op.drop_index(
        op.f('ix_encounter_specialArrangement'), table_name='encounter'
    )
    op.drop_index(op.f('ix_encounter_serviceType'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_serviceProvider'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_reason'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_priority'), table_name='encounter')
    op.drop_index(
        op.f('ix_encounter_plannedStartDate__ext'), table_name='encounter'
    )
    op.drop_index(
        op.f('ix_encounter_plannedStartDate'), table_name='encounter'
    )
    op.drop_index(
        op.f('ix_encounter_plannedEndDate__ext'), table_name='encounter'
    )
    op.drop_index(op.f('ix_encounter_plannedEndDate'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_participant'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_partOf'), table_name='encounter')
    op.drop_index(
        op.f('ix_encounter_modifierExtension'), table_name='encounter'
    )
    op.drop_index(op.f('ix_encounter_meta'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_location'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_length'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_language__ext'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_language'), table_name='encounter')
    op.drop_index(
        op.f('ix_encounter_implicitRules__ext'), table_name='encounter'
    )
    op.drop_index(op.f('ix_encounter_implicitRules'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_identifier'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_fhir_comments'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_extension'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_episodeOfCare'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_dietPreference'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_diagnosis'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_contained'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_class_fhir'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_careTeam'), table_name='encounter')
    op.drop_index(
        op.f('ix_encounter_canonicalEpisodeId'), table_name='encounter'
    )
    op.drop_index(op.f('ix_encounter_basedOn'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_appointment'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_admission'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_actualPeriod'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_account'), table_name='encounter')
    op.drop_table('encounter')
    op.drop_table('diagnoses')
    op.drop_index(
        op.f('ix_deidentifieddatasetdescriptor_version'),
        table_name='deidentifieddatasetdescriptor',
    )
    op.drop_index(
        op.f('ix_deidentifieddatasetdescriptor_url'),
        table_name='deidentifieddatasetdescriptor',
    )
    op.drop_index(
        op.f('ix_deidentifieddatasetdescriptor_records'),
        table_name='deidentifieddatasetdescriptor',
    )
    op.drop_index(
        op.f('ix_deidentifieddatasetdescriptor_license'),
        table_name='deidentifieddatasetdescriptor',
    )
    op.drop_index(
        op.f('ix_deidentifieddatasetdescriptor_language'),
        table_name='deidentifieddatasetdescriptor',
    )
    op.drop_index(
        op.f('ix_deidentifieddatasetdescriptor_generation_date'),
        table_name='deidentifieddatasetdescriptor',
    )
    op.drop_index(
        op.f('ix_deidentifieddatasetdescriptor_dataset_id'),
        table_name='deidentifieddatasetdescriptor',
    )
    op.drop_table('deidentifieddatasetdescriptor')
    op.drop_index(
        op.f('ix_condition_verificationStatus'), table_name='condition'
    )
    op.drop_index(op.f('ix_condition_text'), table_name='condition')
    op.drop_index(op.f('ix_condition_subject'), table_name='condition')
    op.drop_index(op.f('ix_condition_stage'), table_name='condition')
    op.drop_index(op.f('ix_condition_severity'), table_name='condition')
    op.drop_index(
        op.f('ix_condition_recordedDate__ext'), table_name='condition'
    )
    op.drop_index(op.f('ix_condition_recordedDate'), table_name='condition')
    op.drop_index(op.f('ix_condition_participant'), table_name='condition')
    op.drop_index(
        op.f('ix_condition_onsetString__ext'), table_name='condition'
    )
    op.drop_index(op.f('ix_condition_onsetString'), table_name='condition')
    op.drop_index(op.f('ix_condition_onsetRange'), table_name='condition')
    op.drop_index(op.f('ix_condition_onsetPeriod'), table_name='condition')
    op.drop_index(
        op.f('ix_condition_onsetDateTime__ext'), table_name='condition'
    )
    op.drop_index(op.f('ix_condition_onsetDateTime'), table_name='condition')
    op.drop_index(op.f('ix_condition_onsetAge'), table_name='condition')
    op.drop_index(op.f('ix_condition_note'), table_name='condition')
    op.drop_index(
        op.f('ix_condition_modifierExtension'), table_name='condition'
    )
    op.drop_index(op.f('ix_condition_meta'), table_name='condition')
    op.drop_index(op.f('ix_condition_language__ext'), table_name='condition')
    op.drop_index(op.f('ix_condition_language'), table_name='condition')
    op.drop_index(
        op.f('ix_condition_implicitRules__ext'), table_name='condition'
    )
    op.drop_index(op.f('ix_condition_implicitRules'), table_name='condition')
    op.drop_index(op.f('ix_condition_identifier'), table_name='condition')
    op.drop_index(op.f('ix_condition_fhir_comments'), table_name='condition')
    op.drop_index(op.f('ix_condition_extension'), table_name='condition')
    op.drop_index(op.f('ix_condition_evidence'), table_name='condition')
    op.drop_index(op.f('ix_condition_encounter'), table_name='condition')
    op.drop_index(op.f('ix_condition_contained'), table_name='condition')
    op.drop_index(op.f('ix_condition_code'), table_name='condition')
    op.drop_index(op.f('ix_condition_clinicalStatus'), table_name='condition')
    op.drop_index(op.f('ix_condition_category'), table_name='condition')
    op.drop_index(op.f('ix_condition_bodySite'), table_name='condition')
    op.drop_index(
        op.f('ix_condition_abatementString__ext'), table_name='condition'
    )
    op.drop_index(op.f('ix_condition_abatementString'), table_name='condition')
    op.drop_index(op.f('ix_condition_abatementRange'), table_name='condition')
    op.drop_index(op.f('ix_condition_abatementPeriod'), table_name='condition')
    op.drop_index(
        op.f('ix_condition_abatementDateTime__ext'), table_name='condition'
    )
    op.drop_index(
        op.f('ix_condition_abatementDateTime'), table_name='condition'
    )
    op.drop_index(op.f('ix_condition_abatementAge'), table_name='condition')
    op.drop_table('condition')
    op.drop_index(
        op.f('ix_clinicalimpression_text'), table_name='clinicalimpression'
    )
    op.drop_index(
        op.f('ix_clinicalimpression_supportingInfo'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_summary__ext'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_summary'), table_name='clinicalimpression'
    )
    op.drop_index(
        op.f('ix_clinicalimpression_subject'), table_name='clinicalimpression'
    )
    op.drop_index(
        op.f('ix_clinicalimpression_status__ext'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_statusReason'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_status'), table_name='clinicalimpression'
    )
    op.drop_index(
        op.f('ix_clinicalimpression_protocol__ext'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_protocol'), table_name='clinicalimpression'
    )
    op.drop_index(
        op.f('ix_clinicalimpression_prognosisReference'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_prognosisCodeableConcept'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_problem'), table_name='clinicalimpression'
    )
    op.drop_index(
        op.f('ix_clinicalimpression_previous'), table_name='clinicalimpression'
    )
    op.drop_index(
        op.f('ix_clinicalimpression_performer'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_note'), table_name='clinicalimpression'
    )
    op.drop_index(
        op.f('ix_clinicalimpression_modifierExtension'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_meta'), table_name='clinicalimpression'
    )
    op.drop_index(
        op.f('ix_clinicalimpression_language__ext'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_language'), table_name='clinicalimpression'
    )
    op.drop_index(
        op.f('ix_clinicalimpression_implicitRules__ext'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_implicitRules'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_identifier'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_finding'), table_name='clinicalimpression'
    )
    op.drop_index(
        op.f('ix_clinicalimpression_fhir_comments'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_extension'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_encounter'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_effectivePeriod'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_effectiveDateTime__ext'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_effectiveDateTime'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_description__ext'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_description'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_date__ext'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_date'), table_name='clinicalimpression'
    )
    op.drop_index(
        op.f('ix_clinicalimpression_contained'),
        table_name='clinicalimpression',
    )
    op.drop_index(
        op.f('ix_clinicalimpression_changePattern'),
        table_name='clinicalimpression',
    )
    op.drop_table('clinicalimpression')
    op.drop_index(op.f('ix_annotation_time__ext'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_time'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_text__ext'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_text'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_language'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_fhir_comments'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_extension'), table_name='annotation')
    op.drop_index(
        op.f('ix_annotation_authorString__ext'), table_name='annotation'
    )
    op.drop_index(op.f('ix_annotation_authorString'), table_name='annotation')
    op.drop_index(
        op.f('ix_annotation_authorReference'), table_name='annotation'
    )
    op.drop_table('annotation')
    op.drop_index(op.f('ix_aioutput_type'), table_name='aioutput')
    op.drop_index(op.f('ix_aioutput_timestamp'), table_name='aioutput')
    op.drop_index(op.f('ix_aioutput_model_version'), table_name='aioutput')
    op.drop_index(op.f('ix_aioutput_language'), table_name='aioutput')
    op.drop_index(op.f('ix_aioutput_encounter_id'), table_name='aioutput')
    op.drop_index(op.f('ix_aioutput_content'), table_name='aioutput')
    op.drop_table('aioutput')
    # ### end Alembic commands ###
